# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPreencherinformaes():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_preencherinformaes(self):
    self.driver.get("https://ajudaai.pythonanywhere.com/")
    self.driver.set_window_size(1417, 1032)
    self.driver.find_element(By.ID, "icon-forum").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ask-question-button").click()
    self.driver.find_element(By.ID, "titulo").click()
    self.driver.find_element(By.ID, "titulo").send_keys("Grafos em python")
    self.driver.find_element(By.ID, "descricao-pergunta").click()
    self.driver.find_element(By.ID, "descricao-pergunta").send_keys("Alguma biblioteca que possibilite a visualização de grafos em python? #programacao #python")
    self.driver.find_element(By.CSS_SELECTOR, ".botao-cadastro").click()
  
